spring:
  application:
    name: TransactionService

  datasource:
    url: jdbc:postgresql://localhost:5432/transactionsdb
    username: postgres
    password: root

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  kafka:
    enabled: true
    bootstrap-servers: 127.0.0.1:9092
    topic: my-kafka-topic
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest  # remembers the last read offset at application restart
      group-id: my-group-id
  security.oauth2:
    client:
      registration:
        keycloak:
          client-id: luciantestclient
          authorization-grant-type: authorization_code
          scope: openid
      provider:
        keycloak:
          issuer-uri: http://localhost:8082/realms/NotificationRealm
          user-name-attribute: preferred_username
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8082/realms/NotificationRealm
        jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
app:
  transaction-limit: 100.0
