spring:
  application:
    name: TransactionService

  datasource:
    url: jdbc:postgresql://localhost:5432/transactionsdb
    username: postgres
    password: root

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  kafka:
    enabled: true
    bootstrap-servers: 127.0.0.1:9092
    topic: my-kafka-topic
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest  # remembers the last read offset at application restart
      group-id: my-group-id

app:
  transaction-limit: 100.0
